config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  
  resources :users do
    collection {post :import}
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      get 'attendances/sample_log'
      get 'attendances/log'
      patch 'attendances/update_one_month' 
      patch 'attendances/edit_monthly_request'
      get 'basic_info_modification'
      get 'list_of_employees'
      get 'show_confirmation'
      
    end
    resources :attendances do
      get 'edit_overwork_reqest'
      get 'edit_overwork_notice'
      get 'edit_day_notice'
      get 'edit_one_month_notice'
      
      get 'sample'
      get 'sample_edit_overwork_notice'
      get 'sample_edit_day_notice'
      get 'sample_edit_one_month_notice'
      patch 'sample_update_overwork_reqest'
      
      patch 'update_overwork_reqest'
      
      collection do 
        patch 'edit_overwork_approval'
        patch 'edit_day_approval'
        patch 'edit_one_month_approval'
        
      end
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..50 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
        # 保存する
      user.save!
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "department", "employee_number", "uid", "basic_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :show_confirmation, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :basic_info_modification, :list_of_employees]
  before_action :logged_in_user, only: [:show, :index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :list_of_employees]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :list_of_employees, :basic_info_modification, :import]
  before_action :set_one_month, only: [:show, :show_confirmation]
  before_action :admin_not, only:[:show, :edit]

  def index
    @users = User.where.not(id: 1)
    #@users = User.where.not(admin: true) だと、なぜかインポートファイルでadminを空欄で登録した（admin: nil）の社員も弾かれる。意味不明。
  end

  def show
    
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overwork_reqest = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id)
    @edit_day_reqest = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id)
    @edit_monthly_request = Attendance.where(edit_one_month_request_status: "申請中", edit_one_month_request_superior: @user.id)
    #@overwork_sum = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id).count
    #@edit_day_sum = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id).count
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @apply = @user.attendances.find_by(worked_on: @first_day)
  end
  
  def show_confirmation
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overwork_reqest = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id)
    @edit_day_reqest = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id)
    @edit_monthly_request = Attendance.where(edit_one_month_request_status: "申請中", edit_one_month_request_superior: @user.id)
    #@overwork_sum = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id).count
    #@edit_day_sum = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id).count
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @apply = @user.attendances.find_by(worked_on: @first_day)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  def basic_info_modification
  end
  
  def list_of_employees
    @in_attendances = Attendance.where(worked_on: Date.current)
                                 .where(finished_at: nil)
                                 .where.not(started_at: nil)
                                 .includes(:user)
  end
  
  def import
    if params[:file].blank?
      flash[:warning] = "CSVファイルが選択されていません。"
      redirect_to users_url and return
    elsif File.extname(params[:file].original_filename) != ".csv"
          flash[:warning] = "CSVファイルではありません。"
          redirect_to users_url and return
    else
      ActiveRecord::Base.transaction do
        User.import(params[:file])
      end
    end
    flash[:success] = "ユーザー情報をインポートしました。"
    redirect_to users_url
  rescue ActiveRecord::RecordInvalid
      flash[:warning] ="無効な入力データがあった為、追加更新をキャンセルしました。"
      redirect_to users_url
  end
  

  

  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:name,
                                   :email,
                                   :department,
                                   :password,
                                   :employee_number,
                                   :uid,
                                   :designated_work_start_time,
                                   :designated_work_end_time,
                                   :basic_time,
                                   :work_time)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user.html.erb
<%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>
  <!--<!%= render 'shared/error_messages', object: @user %>-->

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
   <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <%= f.submit "更新", class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/basic_info_modification.html.erb
<% provide(:title ) %>
<h1>基本情報の修正</h1>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<div class="csv_holder">
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "CSVインポート", class: "btn btn-primary" %>
  <% end %>
</div>

<% @users.each do |user| %>
    <div>
      <p>
        <div class="col-md-11 col-md-offset-1">
          <!--< if current_user.admin? && !current_user?(user) %>これは使わない方がいい。重くなる。解説は倉谷さんスラック過去質問にて。!current_user?(user)が、管理者を非表示にしている --> 
          <%= user.name %><br>
          <%= link_to "削除", user, method: :delete,
                                    data: { confirm: "削除してもよろしいですか？" },
                                    class: "btn btn-primary btn-default" %><br>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <button type="button" data-toggle="collapse" data-target="#collapse<%= user.id %>" class="btn btn-primary btn-lg">編集</button>
                </h4>
              </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                <div class="panel-body"><%= render 'user', user: user %></div>
              </div>
            </div>
          <!-- end %>-->
        </div>
      </p>
    </div>
<% end %>

app/views/users/list_of_employees.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1>出勤中社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th>社員番号</th>
        <th>氏名</th>
      </tr>
    </thead>
     <tbody>
      <% @in_attendances.each do |in_attendance| %>
        <tr>
          <td><%= in_attendance.user.employee_number %></td>
          <td><%= in_attendance.user.name %></td>
        </tr>
      <% end %>
     </tbody>
  </table>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-left" %>
        【<%= l(@first_day, format: :middle) %>】勤怠管理表
        <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-primary btn-right" %>
        </td>
      <td>
        指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %>
        <br>
        指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td>基本勤務時間：<%= format_basic_info(@user.basic_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>月末日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="btn-users-show">
  <% if current_user.superior? %>
     <% if @edit_monthly_request.present? %>
      <!--= link_to "【サンプル　所属長承認申請のお知らせ】", user_attendance_sample_edit_one_month_notice_path(@user, @attendances) %> -->
      <%= link_to "【所属長承認申請のお知らせ】", user_attendance_edit_one_month_notice_path(@user, @attendances), remote: true, class: "text text-danger" %><%= @edit_monthly_request.count %>件
    <% else %>
      <a>【所属長承認申請のお知らせ】</a>
    <% end %>
    <br>
    <% if @edit_day_reqest.present? %>
      <!--= link_to "【サンプル　勤怠変更のお知らせ】", user_attendance_sample_edit_day_notice_path(@user, @attendances) %>--> 
      <%= link_to "【勤怠変更のお知らせ】", user_attendance_edit_day_notice_path(@user, @attendances), remote: true, class: "text text-danger" %><%= @edit_day_reqest.count %>件
    <% else %>
      <a>【勤怠変更申請のお知らせ】</a>
    <% end %>
    <br>
    <% if @overwork_reqest.present? %>
      <!-- link_to "【サンプル　残業申請のお知らせ】", user_attendance_sample_edit_overwork_notice_path(@user, @attendances) %> -->
      <%= link_to "【残業申請のお知らせ】", user_attendance_edit_overwork_notice_path(@user, @attendances), remote: true, class: "text text-danger" %><%= @overwork_reqest.count %>件
    <% else %>
      <a>【残業申請のお知らせ】</a>
    <% end %>
  <% end %>
  <br>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
    <%= link_to "CSV出力", attendances_edit_one_month_user_path(date: @first_day, format: :csv), class: "btn btn-primary" %>
  <br>
    <!--%= link_to "勤怠修正ログ（承認済）", attendances_log_user_path, remote: true, class: "btn btn-primary" %>--> <%= link_to "勤怠修正ログ（承認済）", attendances_sample_log_user_path, class: "btn btn-primary" %>
</div>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2"></th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="7">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="2">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>残業申請</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    <% @attendances.each do |day| %>
      <tbody>
        <tr>
          <td><%= link_to "残業申請", user_attendance_edit_overwork_reqest_path(@user, day), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% if day.last_edit_day_started_at.nil? && day.edit_day_request_status == "承認" %>
            <td><%= l(day.edit_day_started_at, format: :hour) %></td>
            <td><%= l(day.edit_day_started_at, format: :minute) %></td>
          <% elsif day.edit_day_started_at.present? && day.edit_day_request_status == "承認" %>
            <td><%= l(day.last_edit_day_started_at, format: :hour) %></td>
            <td><%= l(day.last_edit_day_started_at, format: :minute) %></td>
          <% else %>
            <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
            <td><%= l(day.started_at, format: :minute) if day.started_at.present? %></td>
          <% end %>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <% if day.last_edit_day_started_at.nil? && day.edit_day_request_status == "承認" %>
            <td><%= l(day.edit_day_finished_at, format: :hour) %></td>
            <td><%= l(day.edit_day_finished_at, format: :minute) %></td>
          <% elsif day.last_edit_day_finished_at.present? && day.edit_day_request_status == "承認" %>
            <td><%= l(day.last_edit_day_finished_at, format: :hour) %></td>
            <td><%= l(day.last_edit_day_finished_at, format: :minute) %></td>
          <% else %>
            <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
            <td><%= l(day.finished_at, format: :minute) if day.finished_at.present? %></td>
          <% end %>
          <td>
            <% if day.finished_at.present? && day.edit_day_finished_at.nil? %>
              <%= working_times(day.started_at, day.finished_at) %>
            <% elsif day.edit_day_finished_at.present? && day.edit_day_request_status == "承認" %>
              <%= edit_working_times(day.edit_day_started_at, day.edit_day_finished_at, day.next_day) %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time.present? %></td>
          <td><%= l(day.scheduled_end_time, format: :minute) if day.scheduled_end_time.present? %></td>
          <td>
            <% if day.scheduled_end_time.present? %>
              <%= working_overtime(day.scheduled_end_time, @user.designated_work_end_time, day.next_day) %>
            <% end %>
          </td>
          <td><%= day.work_description %></td>
          <td>
            <% if day.scheduled_end_time.present? %>
              <%= superiors(day.over_request_superior).name %>
                <% if day.over_request_status == "申請中" %>
                  へ 
                <% else %>
                  より結果 → 
                <% end %>
              残業 <%= day.over_request_status %>
            <% end %>
            <br>
            <% if day.edit_day_request_superior.present? %>
              <%= User.find(day.edit_day_request_superior).name %>
                <% if day.edit_day_request_status == "申請中" %>
                  へ 
                <% else %>
                  より結果 → 
                <% end %>
              勤怠変更 <%= day.edit_day_request_status %>
            <% end %>
          </td>
          <!--<td><= link_to "サンプル", user_attendance_sample_path(@user, day), class: "btn btn-primary" %></td> <!--あとでこのタブ消す-->
        </tr>
      </tbody>
    <% end %>
  　<!--rowspan:縦結合、colspan：横結合-->
    <tr>
      
      <td></td>
      <td colspan="2"></td>
      <td colspan="6"></td>
      <td></td>
      <td colspan="4"></td>
      <td>
        
        <% if @apply.edit_one_month_request_superior.present? %>
          <%= User.find(@apply.edit_one_month_request_superior).name %>
            <% if @apply.edit_one_month_request_status == "申請中" %>
              へ
            <% else %>
              より結果 →
            <% end %>
          <%= @apply.edit_one_month_request_status %>
        <% end %>
        <br>
        <%= form_with(model: @attendance, url: attendances_edit_monthly_request_user_path(date: @first_day), local: true, method: :patch) do |f| %>
          <%= f.collection_select(:edit_one_month_request_superior, @superiors, :id, :name, { include_blank: "選択してください" }, :required => true) %>
        <br>
        <%= f.submit "変更を送信する", class: "btn btn-primary" %>
        <% end %>
      </td>
      
    </tr>
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-overwork-reqest" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-overwork-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-day-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-one-month-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="log" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/yobi_index.html.erb
-------　チュートリアルの　ユーザー一覧画面
<div class="col-md-10 col-md-offset-1">

  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
          <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

-----------