config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  
  resources :users do
    collection {post :import}
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      get 'attendances/sample_log'
      get 'attendances/log'
      patch 'attendances/update_one_month' 
      patch 'attendances/edit_monthly_request'
      get 'basic_info_modification'
      get 'list_of_employees'
      get 'show_confirmation'
      
    end
    resources :attendances do
      get 'edit_overwork_reqest'
      get 'edit_overwork_notice'
      get 'edit_day_notice'
      get 'edit_one_month_notice'
      
      get 'sample'
      get 'sample_edit_overwork_notice'
      get 'sample_edit_day_notice'
      get 'sample_edit_one_month_notice'
      patch 'sample_update_overwork_reqest'
      
      patch 'update_overwork_reqest'
      
      collection do 
        patch 'edit_overwork_approval'
        patch 'edit_day_approval'
        patch 'edit_one_month_approval'
        
      end
    end
  end
  
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
  before_action :admin_user
  
  def index
    @bases = Base.all
  end
  
  def edit
    @base = Base.find(params[:id])
  end
  
  def new
    @base = Base.new
  end
  
  def create
    @base = Base.new(base_params)
    if @base.save
      flash[:success] = "拠点情報が追加されました。"
      redirect_to bases_url
    else
      flash[:danger] = "拠点情報の更新に失敗しました。"
      render :new
    end
  end
  
  def update
    @base = Base.find(params[:id])
    if @base.update_attributes(base_params)
      flash[:success] = "拠点情報を更新しました。"
      redirect_to bases_url
    else
      flash[:danger] = '拠点情報の更新に失敗しました。'
      render :edit
    end
  end
  
  def destroy
    @base = Base.find(params[:id])
    @base.destroy
    flash[:success] = "#{@base.base_name}のデータを削除しました。"
    redirect_to bases_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
  end
  
  private
  
  def base_params
    params.require(:base).permit(:base_id, :base_name, :base_type)
  end
    
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/views/bases/_edit_basic_info.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">拠点情報の追加</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with model: @base, url: bases_path, local: true do |f| %>

            <%= f.label :base_id, class: "label-user--edit" %>
            <%= f.text_field :base_id, class: "form-control" %>
            
            <%= f.label :base_name, class: "label-user--edit" %>
            <%= f.text_field :base_name, class: "form-control" %>
            
            <%= f.label :base_type, class: "label-user--edit" %>
            <%= f.text_field :base_type, class: "form-control" %>
            
            <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bases/edit.html.erb
<h1>拠点情報の更新</h1>

app/views/bases/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/bases/index.html.erb
<div class="container">
  <h1>拠点一覧</h1>
    <table class="table table-bordered table-condensed user-table">
      <tbody>
        <thead>
          <tr>
            <td></td>
            <td></td>
            <td>拠点番号</td>
            <td>拠点名</td>
            <td>勤怠種類</td>
          </tr>
        </thead>
        
        <% @bases.each do |base| %>
          <tr>
            <td>
              <%= link_to "修正", edit_basis_url(base) , class: "btn btn-primary" %>
            </td>
            <td><%= link_to "削除", base, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %></td>
            <td><%= base.base_id %></td>
            <td><%= base.base_name %></td>
            <td><%= base.base_type %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "拠点情報の追加", new_basis_url, class: "btn btn-lg btn-primary" %>
</div>

<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/bases/new.html.erb
<h1>拠点情報の追加</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @base, url: bases_path, local: true do |f| %>

      <%= f.label :base_id, class: "label-user--edit" %>
      <%= f.text_field :base_id, class: "form-control" %>
      
      <%= f.label :base_name, class: "label-user--edit" %>
      <%= f.text_field :base_name, class: "form-control" %>
      
      <%= f.label :base_type, class: "label-user--edit" %>
      <%= f.text_field :base_type, class: "form-control" %>
      
      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>
</div>