config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  
  resources :users do
    collection {post :import}
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      get 'attendances/sample_log'
      get 'attendances/log'
      patch 'attendances/update_one_month' 
      patch 'attendances/edit_monthly_request'
      get 'basic_info_modification'
      get 'list_of_employees'
      get 'show_confirmation'
      
    end
    resources :attendances do
      get 'edit_overwork_reqest'
      get 'edit_overwork_notice'
      get 'edit_day_notice'
      get 'edit_one_month_notice'
      
      get 'sample'
      get 'sample_edit_overwork_notice'
      get 'sample_edit_day_notice'
      get 'sample_edit_one_month_notice'
      patch 'sample_update_overwork_reqest'
      
      patch 'update_overwork_reqest'
      
      collection do 
        patch 'edit_overwork_approval'
        patch 'edit_day_approval'
        patch 'edit_one_month_approval'
        
      end
    end
  end
  
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  require 'csv'

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 退勤時間が存在しない場合、出勤時間は無効
  validate :started_at_is_invalid_without_a_finished_at
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  # 2回目の編集申請時間の、出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :last_edit_day_started_at_than_last_edit_day_finished_at_fast_if_invalid
  
  validate :sample1
  
  validate :sample2
  
  #validate :sample3
  
  

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if edit_day_started_at.blank? && edit_day_finished_at.present?
  end
  
  def started_at_is_invalid_without_a_finished_at
    errors.add(:finished_at, "が必要です") if edit_day_started_at.present? && edit_day_finished_at.blank?
  end

  def started_at_than_finished_at_fast_if_invalid
    if edit_day_started_at.present? && edit_day_finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if edit_day_started_at > edit_day_finished_at
    end
  end
  
  def last_edit_day_started_at_than_last_edit_day_finished_at_fast_if_invalid
    if last_edit_day_started_at.present? && last_edit_day_finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if last_edit_day_started_at > last_edit_day_finished_at
    end
  end
  
  def sample1
    errors.add(:started_at, "が必要です") if last_edit_day_started_at.blank? && last_edit_day_finished_at.present?
  end
  
  def sample2
    errors.add(:finished_at, "が必要です") if last_edit_day_started_at.present? && last_edit_day_finished_at.blank?
  end
  
  def sample3 #これやると、出勤退勤ボタンが押せなくなった
   errors.add(:finished_at, "が必要です") if last_edit_day_started_at.blank? && last_edit_day_finished_at.blank?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :edit_monthly_request]
  before_action :logged_in_user, only: [:update, :edit_one_month, :edit_overwork_reqest, :update_overwork_reqest, :sample_update_overwork_reqest, :edit_monthly_request]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: [:edit_one_month, :edit_monthly_request]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  def edit_one_month
    @superiors = User.where(superior: true).where.not(id: @user.id)
     respond_to do |format|
      format.html
      format.csv do |csv|
        send_attendance_csv(@attendances)
      end
    end
  end

  def update_one_month
    c1 = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      attendances_params.each do |id, item|
        attendance = Attendance.find(id) # Attendanceテーブルから1つのidを見つける
        if item[:edit_day_request_superior].present?
          item[:edit_day_request_status] = "申請中"
          c1 += 1
          attendance.update_attributes!(item)
        end
      end
    end
    if c1 > 0
      flash[:success] = "勤怠編集を#{c1}件、申請しました。"
      redirect_to user_url(date: params[:date])
    else
      flash[:danger] = "上長を選択してください"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
        
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def send_attendance_csv(attendances)
    csv_data = CSV.generate do |csv|
      header = %w(日付 出社 退社)
      csv << header
      attendances.each do |attendance|
        values = [
          l(attendance.worked_on, format: :short),
          if attendance.started_at.present?
          l(attendance.started_at, format: :time) end ,
          if attendance.finished_at.present?
          l(attendance.finished_at, format: :time)  end,
          ]
          csv << values
        end
      end
      send_data(csv_data, filename: "勤怠一覧表.csv")
  end
  
  #残業申請フォーム、ポップアップの表示
  def edit_overwork_reqest
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:attendance_id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
  
  # ポップアップから残業申請する機能
  def update_overwork_reqest
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:attendance_id])
    params[:attendance][:over_request_status] = "申請中"
    if overwork_params[:scheduled_end_time].present?
      @attendance.update_attributes(overwork_params)
      flash[:info] = "残業申請をしました。"
    else
      flash[:danger] = "残業申請をキャンセルしました。"
    end
    redirect_to @user
  end
  
  # 残業申請のHTMLページ表示
  def sample
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:attendance_id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
  end
  
  # 残業申請をHTMLページから申請する機能
  def sample_update_overwork_reqest
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:attendance_id])
    params[:attendance][:over_request_status] = "申請中"
    if overwork_params[:scheduled_end_time].present?
      @attendance.update_attributes(overwork_params)
      flash[:info] = "残業申請をしました。"
    else
      flash[:danger] = "残業申請をキャンセルしました。"
    end
    redirect_to @user
  end
  
  # 上長側、残業申請通知画面をHTMLで表示する機能
  def sample_edit_overwork_notice
    @user = User.find(params[:user_id])
    @attendances = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
    #@users = User.joins(:attendances).where(attendances:{over_request_status: "申請中", over_request_superior: @user.id}).group(:user_id)
    #モデル名.joins(:関連名).group(:).where(カラム名: 値)
    #groupメソッドとは、指定したカラムのデータの種類ごとに、データをまとめることが出来るメソッドです。
    #group_byメソッド,要素をグループ分けするためのメソッド、※引数に「&:」が必要！
  end
  
  # 上長側、残業申請通知画面をポップアップで表示
  def edit_overwork_notice
    @user = User.find(params[:user_id])
    @attendances = Attendance.where(over_request_status: "申請中", over_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
  end
  
  # 上長側、残業申請結果を送信する機能
  def edit_overwork_approval
    @user = User.find(params[:user_id])
    c1 = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      overwork_approval_params.each do |id, item|
        attendance = Attendance.find(id)
        if item[:change] == "1"
          c1 += 1
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:success] = "残業申請の結果を#{c1}件、送信しました"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to @user
  end
  
  # 上長側、勤怠変更申請のお知らせ一覧をHTMLで表示
  def sample_edit_day_notice
    @user = User.find(params[:user_id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @attendances = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
  end
  
  #勤怠申請のお知らせ一覧モーダルで
  def edit_day_notice
    @user = User.find(params[:user_id])
    @superiors = User.where(superior: true).where.not(id: @user.id)
    @attendances = Attendance.where(edit_day_request_status: "申請中", edit_day_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
  end
  
  #勤怠変更申請結果を送信するアクション
  def edit_day_approval
    @user = User.find(params[:user_id])
    c1 = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      edit_day_approval_params.each do |id, item|
        attendance = Attendance.find(id)
        if item[:edit_day_check_confirm] == "1"
          c1 += 1
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:success] = "勤怠編集申請の#{c1}件、結果を送信しました"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to @user
  end
  
  # 右下の月の勤怠申請アクション
  def edit_monthly_request
    #@user = User.find(params[:user_id])
    #@attendance = Attendance.find_by(params[:date])
    #@first_day = params[:date].nil? ? Date.current.beginning_of_month : params[:date].to_date #月の初日を取得
    @apply = @user.attendances.find_by(worked_on: params[:date])
    params[:edit_one_month_request_status] = "申請中"
    @apply.update_attributes(monthly_request_params)
    flash[:success] = "1ヶ月分の勤怠情報を申請しました。"
    redirect_to user_url(current_user)
  end
  
  # 月の勤怠申請のお知らせ画面　HTMLで表示
  def sample_edit_one_month_notice
    @user = User.find(params[:user_id])
    @attendances = Attendance.where(edit_one_month_request_status: "申請中", edit_one_month_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
  end
  
  # 月の勤怠申請のお知らせ画面　モーダルで表示
  def edit_one_month_notice
    @user = User.find(params[:user_id])
    @attendances = Attendance.where(edit_one_month_request_status: "申請中", edit_one_month_request_superior: @user.id).order(:worked_on).group_by(&:user_id)
  end
  
  # 月の勤怠申請結果を送信　アクション
  def edit_one_month_approval
    @user = User.find(params[:user_id])
    c1 = 0
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      monthly_approval_params.each do |id, item|
        attendance = Attendance.find(id)
        if item[:edit_one_month_check_confirm] == "1"
          c1 += 1
          attendance.update_attributes!(item)
        end
      end
    end
    flash[:success] = "所属長承認申請の結果を#{c1}件、送信しました"
    redirect_to @user
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to @user
  end
  
  # 勤怠修正ログ画面をHTMLで表示
  def sample_log
    @user = User.find(params[:id]) #これ無くても機能出来た
    #@search = Attendance.where(edit_day_request_status: "承認").order(:worked_on).ransack(params[:q]) これでも出来る
    @search = @user.attendances.where(edit_day_request_status: "承認").order(:worked_on).ransack(params[:q]) #矢木さんに教えてもらったコード
    @attendances = @search.result
  end
  
  # 勤怠修正ログ画面をモーダルで表示
  def log
    @user = User.find(params[:id])
    @search = @user.attendances.where(edit_day_request_status: "承認").order(:worked_on).ransack(params[:q])
    @attendances = @search.result
  end
  

  private
  
    # beforeフィルター

    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at,
                                                 :finished_at,
                                                 :note,
                                                 :next_day,
                                                 :edit_day_request_superior,
                                                 :edit_day_request_status,
                                                 :edit_day_started_at,
                                                 :edit_day_finished_at,
                                                 :last_edit_day_started_at,
                                                 :last_edit_day_finished_at])[:attendances]
    end
    
    def overwork_params
      params.require(:attendance).permit(:scheduled_end_time, :work_description, :next_day, :over_request_superior, :over_request_status)
    end
    
    def overwork_approval_params
      params.require(:user).permit(attendances: [:over_request_status, :change])[:attendances]
    end
    
    def edit_day_approval_params

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(started_at, finished_at)
    #if next_day == "1"
      #format("%.2f", (((finished_at - started_at) / 60) / 60.0) +24)
    #elsif next_day == "0"
      format("%.2f", (((finished_at - started_at) / 60) / 60.0))
    #end
  end
  
  def edit_working_times(edit_day_started_at, edit_day_finished_at, next_day)
    if next_day == "1"
      format("%.2f", (((edit_day_finished_at - edit_day_started_at) / 60) / 60.0) +24)
    elsif next_day == "0"
      format("%.2f", (((edit_day_finished_at - edit_day_started_at) / 60) / 60.0))
    end
  end
  
  def working_overtime(scheduled_end_time, designated_work_end_time, next_day)
    if  next_day == "1"
      format("%.2f", (((scheduled_end_time - designated_work_end_time) / 60) / 60.0) +24)
    elsif next_day == "0"
      format("%.2f", ((scheduled_end_time - designated_work_end_time) / 60) / 60.0)
    end
  end
  
  def superiors(over_request_superior)
    User.find(over_request_superior)
  end
  

  
end

app/views/attendances/_edit_day_notice.html.erb
<%= form_with(model: @user, url: edit_day_approval_user_attendances_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <% @attendances.each do |id, attendances| %>
        <% user = User.find(id) %>
        <h4 class="modal-title center">【<%= user.name %>】からの勤怠変更申請</h4>
          <div class="modal-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th rowspan="3">日付</th>
                  <th rowspan="3">曜日</th>
                  <th colspan="4">変更前</th>
                  <th colspan="4">変更後</th>
                  <th rowspan="3">備考</th>
                  <th rowspan="3">指示者確認印</th>
                  <th rowspan="3">変更</th>
                  <th rowspan="3">勤怠を確認する</th>
                </tr>
                <tr>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                </tr>
                <tr>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                </tr>
              </thead>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |item| %>
                  <tbody>
                    <tr>
                      <td><%= l(day.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                      <td><%= l(day.edit_day_started_at, format: :hour) %></td>
                      <td><%= l(day.edit_day_started_at, format: :minute) %></td>
                      <td><%= l(day.edit_day_finished_at, format: :hour) %></td>
                      <td><%= l(day.edit_day_finished_at, format: :minute) %></td>
                      <td><%= l(day.last_edit_day_started_at, format: :hour) if day.last_edit_day_started_at.present? %></td>
                      <td><%= l(day.last_edit_day_started_at, format: :minute) if day.last_edit_day_started_at.present? %></td>
                      <td><%= l(day.last_edit_day_finished_at, format: :hour) if day.last_edit_day_finished_at.present? %></td>
                      <td><%= l(day.last_edit_day_finished_at, format: :minute) if day.last_edit_day_finished_at.present? %></td>
                      <td><%= day.work_description %></td>
                      <td><%= item.select :edit_day_request_status, ['なし', '申請中', '承認', '否認'] %></td>
                      <td><%= item.check_box :edit_day_check_confirm, id: "test" %></td>
                      <td><%= link_to "確認", show_confirmation_user_path(id), target: :_blank, class: "btn btn-primary" %></td>
                    </tr>
                  </tbody>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
      <div class= center>
        <%= submit_tag "変更を送信する" %>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_one_month_notice.html.erb
<%= form_with(model: @user, url: edit_one_month_approval_user_attendances_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <% @attendances.each do |id, attendances| %>
        <% user = User.find(id) %>
        <h4 class="modal-title center">【<%= user.name %>】からの１ヶ月分勤怠申請d</h4>
          <div class="modal-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>月</th>
                  <th>指示者確認印</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |item| %>
                  <tbody>
                    <tr>
                      <td><%= l(day.worked_on, format: :middle) %></td>
                      <td><%= item.select :edit_one_month_request_status, ['なし', '申請中', '承認', '否認'] %></td>
                      <td><%= item.check_box :edit_one_month_check_confirm, id: "test" %></td>
                      <td><%= link_to "確認", show_confirmation_user_path(id), target: :_blank, class: "btn btn-primary" %></td>
                    </tr>
                  </tbody>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
      <div class= center>
        <%= submit_tag "変更を送信する" %>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_overwork_notice.html.erb
<%= form_with(model: @user, url: edit_overwork_approval_user_attendances_path(@user), local: true, method: :patch) do |f| %>
  <div class="modal-dialog modal-lg modal-dialog-center">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <% @attendances.each do |id, attendances| %>
        <% user = User.find(id) %>
        <h4 class="modal-title center">【<%= user.name %>】からの残業申請　サンプル</h4>
          <div class="modal-body">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>時間外時間</th>
                  <th>業務処理内容</th>
                  <th>指示者確認印</th>
                  <th>変更</th>
                  <th>勤怠を確認する</th>
                </tr>
              </thead>
              <% attendances.each do |day| %>
                <%= f.fields_for "attendances[]", day do |item| %>
                  <tbody>
                    <tr>
                      <td><%= l(day.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                      <td><%= l(day.scheduled_end_time, format: :time) %></td>
                      <td><%= working_overtime(day.scheduled_end_time, user.designated_work_end_time, day.next_day) %></td>
                      <td><%= day.work_description %></td>
                      <td><%= item.select :over_request_status, ['なし', '申請中', '承認', '否認'] %></td>
                      <td><%= item.check_box :change, id: "test" %></td>
                      <td><%= link_to "確認", show_confirmation_user_path(id), target: :_blank, class: "btn btn-primary" %></td>
                    </tr>
                  </tbody>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
      <div class= center>
        <%= submit_tag "変更を送信する" %>
      </div>
    </div>
  </div>
<% end %>

app/views/attendances/_edit_overwork_reqest.html.erb
<% provide(:button_text, '変更を送信する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <%= form_with(model: @attendance, url: user_attendance_update_overwork_reqest_path(@user, @attendance), local: true, method: :patch) do |f| %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>日付</th>
              <th>曜日</th>
              <th>終了予定時間</th>
              <th>翌日</th>
              <th>業務処理内容</th>
              <th>指示者確認印</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= l(@attendance.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
              <td><%= f.time_field :scheduled_end_time, class: 'form-control' %></td>
              <td><%= f.check_box :next_day, id: "test" %></td>
              <td><%= f.text_field :work_description, class: 'form-control' %></td>
              <td><%= f.collection_select(:over_request_superior, @superiors, :id, :name, { include_blank: "選択してください" }, :required => true) %></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "送信する", class: "btn-btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認印</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            
              <tr>
                <td><%= l(day.worked_on, format: :short) %></td>
                <td><%= $days_of_the_week[day.worked_on.wday] %></td>
                  <% if !current_user.admin? && (Date.current < day.worked_on) %>
                    <td><%= attendance.time_field :edit_day_started_at, readonly: true, class: "form-control" %></td>
                    <td><%= attendance.time_field :edit_day_finished_at, readonly: true, class: "form-control" %></td>
                  <% else %>
                    <td>
                      <% if day.edit_day_started_at.present? %>
                        <%= attendance.time_field :last_edit_day_started_at, class: "form-control" %>
                      <% else %>
                        <%= attendance.time_field :edit_day_started_at, class: "form-control" %>
                      <% end %>
                    </td>
                    <td>
                      <% if day.edit_day_finished_at.present? %>
                        <%= attendance.time_field :last_edit_day_finished_at, class: "form-control" %>
                      <% else %>
                        <%= attendance.time_field :edit_day_finished_at, class: "form-control" %>
                      <% end %>
                    </td>
                  <% end %>
                <td><%= attendance.check_box :next_day, id: "test" %></td>
                <td>
                  <% if day.started_at.present? && day.finished_at.present? %>
                    <%= working_times(day.started_at, day.finished_at) %>
                  <% end %>
                </td>
                <td><%= attendance.text_field :note, class: "form-control" %></td>
                <td>
                  <%= attendance.collection_select(:edit_day_request_superior, @superiors, :id, :name, { include_blank: "選択してください", selected: nil }) %>
                </td>
              </tr>
            
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/sample.html.erb
<% provide(:button_text, '送信') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">残業申請のサンプル</h1>
    </div>
    <div class="modal-body">
      <%= form_with(model: @attendance, url: user_attendance_sample_update_overwork_reqest_path(@user, @attendance), local: true, method: :patch) do |f| %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>日付</th>
              <th>曜日</th>
              <th>終了予定時間</th>
              <th>翌日</th>
              <th>業務処理内容</th>
              <th>指示者確認印</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= l(@attendance.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
              <td><%= f.time_field :scheduled_end_time, class: 'form-control' %></td>
              <td><%= f.check_box :next_day, id: "test" %></td>
              <td><%= f.text_field :work_description, class: 'form-control' %></td>
              <td><%= f.collection_select(:over_request_superior, @superiors, :id, :name, { include_blank: "選択してください" }, :required => true) %></td>
            </tr>
          </tbody>
        </table>
        <%= f.submit "送信する", class: "btn-btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
</div>