config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases
  
  resources :users do
    collection {post :import}
    
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      get 'attendances/sample_log'
      get 'attendances/log'
      patch 'attendances/update_one_month' 
      patch 'attendances/edit_monthly_request'
      get 'basic_info_modification'
      get 'list_of_employees'
      get 'show_confirmation'
      
    end
    resources :attendances do
      get 'edit_overwork_reqest'
      get 'edit_overwork_notice'
      get 'edit_day_notice'
      get 'edit_one_month_notice'
      
      get 'sample'
      get 'sample_edit_overwork_notice'
      get 'sample_edit_day_notice'
      get 'sample_edit_one_month_notice'
      patch 'sample_update_overwork_reqest'
      
      patch 'update_overwork_reqest'
      
      collection do 
        patch 'edit_overwork_approval'
        patch 'edit_day_approval'
        patch 'edit_one_month_approval'
        
      end
    end
  end
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? && current_user.admin? %>
      <%= link_to "Attendance App", users_path, id: "logo" %>
    <% else %>
      <%= link_to "Attendance App", current_user, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? && current_user.admin? %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "出勤社員一覧", list_of_employees_user_path(current_user) %></li>
          <li><%= link_to "拠点情報の修正", bases_url %></li>
          <li><%= link_to "基本情報の修正", basic_info_modification_user_path(current_user) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% elsif logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              メニュー <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!-- HTML shimがこの1行で収まる -->
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <!-- headerの内容がこの1行で収まる -->
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>